btcimg/apps/communications/urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView

from .views import HomeView

urlpatterns = patterns(
    '',
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^privacy/$', TemplateView.as_view(template_name="communications/privacy.html")),
    url(r'^terms/$', TemplateView.as_view(template_name="communications/terms.html")),
)

btcimg/apps/locker/urls.py
from django.conf.urls import patterns, url

from .views import AssetView, AssetCreate, AssetList

urlpatterns = patterns('',
    url(r'^create/', AssetCreate.as_view(), name='asset-create'),
    url(r'^list/', AssetList.as_view(), name='asset-list'),
    url(r'^img/(?P<slug>[\w\-\.\~\+&,]+)/', AssetView.as_view(), name='asset-detail'),
)

btcimg/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/', include('btcimg.apps.api.urls', namespace='api')),
    url(r'^', include('btcimg.apps.locker.urls', namespace='locker')),
    url(r'^', include('btcimg.apps.communications.urls', namespace='communications')),
)

if settings.DEBUG:
# for static assets during development
    urlpatterns += staticfiles_urlpatterns()
    # for media assets during development
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

btcimg/apps/communications/views.py
from django.views import generic


class HomeView(generic.TemplateView):
    template_name = 'communications/home.html'

btcimg/apps/communications/templates/base.html
<!DOCTYPE html>

<html>
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
	<title>{% block title %}BTC Img{% endblock %}</title>

	{% load compress %}

	<link rel="icon" type="image/png" href="{{ STATIC_URL }}img/favicon.png">

	{% compress css %}
		<link rel="stylesheet" href="{{ STATIC_URL }}scss/_bootstrap.scss" type="text/x-scss" media="all" />
		<link rel="stylesheet" href="{{ STATIC_URL }}scss/base.scss" type="text/x-scss" media="all" />
		{% block css %}{% endblock %}
	{% endcompress %}
	
	{% block uncompressed_css %}{% endblock %}
		
	{% compress js %}
		<script src="{{ STATIC_URL }}js/jquery-2.1.3.min.js"></script>
		<script src="{{ STATIC_URL }}js/bootstrap.min.js"></script>
		{% block js %}
		{% endblock %}
	{% endcompress %}

	{% block uncompressed_js %}{% endblock %}
	
</head>

<body class="{% block bodyClasses %}{% endblock %}">
	<div class="wrap">
		{% include "nav.html" %}

		<div class="main-content">
			{% block full_content %}{% endblock %}
			<div class="container main-container">
			    {% block content %}{% endblock %}
			</div>
		</div>
	</div>
	<footer class="footer">
		<div class="container">
			<p class="text-muted">
				Built by <a target="_" class="" href="http://kevinriggen.com">Kevin</a> | <a href="https://github.com/kvnn/btcimg"><img src="{{ STATIC_URL }}img/GitHub-Mark-32px.png"></a> | <a class="" href="/privacy">privacy</a>
			</p>
		</div>	
	</footer>


</body>


</html>

btcimg/apps/communications/templates/form.html
{% load bootstrap %}

{% block content %}
<form enctype="multipart/form-data" class="col-md-6" method="POST" action="">{% csrf_token %}
    {% csrf_token %}
    {{ form|bootstrap }}
    <div class="form-group">
      <button type="submit" class="btn btn-primary">{% firstof submit_text "Submit" %}</button>
    </div>
</form>
{% endblock %}

btcimg/apps/communications/templates/nav.html
<nav class="navbar navbar-default">
  <div class="container">
    <h3 class="nav-title"><a href="/">btc<span>img</span></a></h3>
    <h4><a href="{% url 'locker:asset-create' %}"><i class="glyphicon glyphicon-cloud-upload"></i></a></h4>
  </div>
</nav>